MERGE (n:PhysicalDisabilityHandbook {id: "nb_physical_disability_handbook"}) SET n += {name: "身体障害者手帳", source: "ai-no-techo", type_label: "身体障害者手帳"};
MERGE (n:BunkyoDisabilityWelfareDivision {id: "nb_bunkyo_disability_welfare_division"}) SET n += {name: "文京区 障害福祉課", source: "disability-welfare-division", type_label: "文京区 障害福祉課"};
MERGE (n:ContactWindow {id: "contact_disability_welfare"}) SET n += {name: "障害福祉課 相談の窓口", source: "disability-welfare-division", type_label: "相談の窓口"};
MERGE (n:MentalDisabilityHandbook {id: "nb_mental_disability_handbook"}) SET n += {name: "精神障害者保健福祉手帳", source: "shintaishogaisha-techo", type_label: "精神障害者保健福祉手帳"};
MERGE (n:BunkyoPreventionMeasuresDivision {id: "nb_bunkyo_prevention_measures_division"}) SET n += {name: "文京区 予防対策課", source: "disability-welfare-division", type_label: "文京区 予防対策課"};
MERGE (n:PublicHealthServiceCenter {id: "nb_public_health_service_center"}) SET n += {name: "保健サービスセンター", source: "disability-welfare-division", type_label: "保健サービスセンター"};
MERGE (n:AiNoTecho {id: "nb_ai_no_techo"}) SET n += {name: "愛の手帳（知的障害者手帳）", source: "handbooks", type_label: "愛の手帳（知的障害者手帳）"};
MERGE (n:ChildConsultationCenter {id: "nb_child_consultation_center"}) SET n += {name: "児童相談所", source: "disability-welfare-division", type_label: "児童相談所"};
MERGE (n:AutomobileAccidentSupportSystem {id: "svc_automobile_accident_support"}) SET n += {name: "自動車事故被害者支援制度", source: "allowances-pensions-loans", type_label: "自動車事故被害者支援制度"};
MERGE (n:DisabilityFacility {id: "nb_bunbun_marushe"}) SET n += {name: "ぶんぶんまるしぇ", source: "bunkyo-city", type_label: "障害者施設"};
MERGE (n:ChronicPediatricDiseaseDailyLivingAidBenefit {id: "svc_chronic_pediatric_disease_daily_living_aid"}) SET n += {name: "小児慢性特定疾病児童日常生活用具給付", source: "chronic-pediatric-disease-medical-expense-subsidy,nichijo-seikatsu-yogu-no-kyufu", type_label: "小児慢性特定疾病児童日常生活用具給付", pageNumber: 75};
MERGE (n:ParkingFeeReductionSystem {id: "svc_parking_fee_reduction"}) SET n += {name: "駐車料金減額制度", source: "chusha-kinshi-no-taisho-jogai", type_label: "駐車料金減額制度", pageNumber: 113};
MERGE (n:AnshinConsultationService {id: "svc_anshin_consultation"}) SET n += {name: "手をつなぐあんしん相談", source: "consultation-windows", type_label: "手をつなぐあんしん相談"};
MERGE (n:ReductionSystem {id: "svc_daily_living_aid_reduction"}) SET n += {name: "日常生活用具給付事業の利用者負担減免", source: "daily-living-aids-benefit", type_label: "軽減制度"};
MERGE (n:InformationSupport {id: "svc_yometeru"}) SET n += {name: "ヨメテル(文字表示電話サービス)", source: "denwa-relay-service", type_label: "情報支援"};
MERGE (n:EarMark {id: "svc_ear_mark"}) SET n += {name: "耳マーク", source: "ear-mark", type_label: "耳マーク"};
MERGE (n:EvacuationSupportRegistry {id: "svc_evacuation_registry"}) SET n += {name: "避難行動要支援者名簿", source: "fukushi-hinanjo-no-secchi", type_label: "避難行動要支援者名簿", pageNumber: 94};
MERGE (n:HelpMark {id: "svc_help_mark"}) SET n += {name: "ヘルプマーク", source: "heart-plus-mark,help-card", type_label: "ヘルプマーク"};
MERGE (n:HelpCard {id: "svc_help_card"}) SET n += {name: "ヘルプカード", source: "help-mark", type_label: "ヘルプカード", pageNumber: 98};
MERGE (n:MedicalCareChildRespiteService {id: "svc_respite_service"}) SET n += {name: "医療的ケア児在宅レスパイト事業", source: "iryoteki-care-ji-no-shakai-taiken-program", type_label: "医療的ケア児在宅レスパイト事業", pageNumber: 85};
MERGE (n:MedicalCareChildSupportRoomHimawari {id: "svc_himawari_room"}) SET n += {name: "医療的ケア児支援ルームひまわり", source: "iryoteki-care-ji-zaitaku-respite-jigyo", type_label: "医療的ケア児支援ルームひまわり", pageNumber: 86};
MERGE (n:MagneticLoopInstallationService {id: "svc_magnetic_loop_installation"}) SET n += {name: "磁気ループの設置", source: "onsei-yudo-sochi-no-secchi", type_label: "磁気ループ設置サービス", pageNumber: 104};
MERGE (n:BrailleBookBenefitSystem {id: "svc_braille_book_benefit"}) SET n += {name: "点字図書の給付", source: "kuritsu-toshokan-no-riyo-shien", type_label: "点字図書給付制度", pageNumber: 101};
MERGE (n:DrivingLicenseAcquisitionSubsidy {id: "svc_driving_license_acquisition_subsidy"}) SET n += {name: "心身障害者自動車運転免許取得経費補助", source: "shintai-shogaisha-jidousha-kaizo-hi-josei", type_label: "運転免許取得費助成", pageNumber: 110};
MERGE (n:NighttimeMentalHealthPhoneConsultation {id: "svc_nighttime_mental_consultation"}) SET n += {name: "夜間こころの電話相談", source: "tokyo-psychiatric-mental-health-center", type_label: "夜間精神保健電話相談"};
MATCH (a {id: "nb_physical_disability_handbook"}), (b {id: "nb_bunkyo_disability_welfare_division"}) CREATE (a)-[:hasApplicationWindow]->(b);
MATCH (a {id: "nb_bunkyo_disability_welfare_division"}), (b {id: "contact_disability_welfare"}) CREATE (a)-[:hasContactInfo]->(b);
MATCH (a {id: "nb_mental_disability_handbook"}), (b {id: "nb_bunkyo_prevention_measures_division"}) CREATE (a)-[:hasApplicationWindow]->(b);
MATCH (a {id: "nb_mental_disability_handbook"}), (b {id: "nb_public_health_service_center"}) CREATE (a)-[:hasApplicationWindow]->(b);
MATCH (a {id: "nb_ai_no_techo"}), (b {id: "nb_child_consultation_center"}) CREATE (a)-[:hasAssessmentLocationForMinors]->(b);